<html>
<head>
<title>Exception Handling in Java</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Java中的异常处理</h1>
<blockquote>原文：<a href="https://medium.com/geekculture/exception-handling-in-java-c75f1eb15f7b?source=collection_archive---------23-----------------------#2021-05-17">https://medium.com/geekculture/exception-handling-in-java-c75f1eb15f7b?source=collection_archive---------23-----------------------#2021-05-17</a></blockquote><div><div class="ds gw gx gy gz ha"/><div class="hb hc hd he hf"><div class=""/><figure class="ev ex ig ih ii ij er es paragraph-image"><div role="button" tabindex="0" class="ik il di im bf in"><div class="er es if"><img src="../Images/511c090a3f9e12e802543d86793d671e.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*rEo6sR6K9uj_vTqDcxD8rA.png"/></div></div></figure><p id="967d" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated"><strong class="is hj">异常:</strong>Java中的异常是一种不希望发生的事件，它会扰乱程序的正常流程。这些是可以恢复的。程序员可以处理这种情况，并采取必要的纠正措施。其中一些是NullPointerException、SQLException、ClassNotFoundException和RuntimeException。例如，被零除的数是一种RuntimeException。</p><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="a255" class="jx jy hi jt b fi jz ka l kb kc">public class Example {<br/>   public static void main(String[] args){<br/>      int num1 = 100;<br/>      int num2 = 0;<br/>      int result = num1 / num2;<br/>   }<br/>}</span><span id="c767" class="jx jy hi jt b fi kd ka l kb kc">Output: java.lang.ArithmeticException: / by zero<br/>        at Example.main(Example.java:5)</span></pre><p id="d227" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated"><strong class="is hj">错误:</strong>主要是系统资源不足导致的问题。这些是不可恢复的。其中一些是StackOverflowError、VirtualMachineError和OutofMemoryError。例如，StackOverflow错误是一个无限递归错误，其中函数调用自己的次数太多，以至于存储与每次调用相关的变量和信息所需的空间超过了<strong class="is hj">堆栈</strong>的容量。</p><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="f2c8" class="jx jy hi jt b fi jz ka l kb kc">public class Example {<br/>   public static void main(String[] args){<br/>      recursiveMethod();<br/>   }<br/>   public static void recursiveMethod(){<br/>      while(true){<br/>         recursiveMethod();<br/>      }<br/>   }<br/>}</span><span id="ce42" class="jx jy hi jt b fi kd ka l kb kc">Output: Exception in thread "main" java.lang.StackOverflowError<br/> at ErrorExample.recursiveMethod(Main.java:7)<br/> at ErrorExample.recursiveMethod(Main.java:7)<br/> at ErrorExample.recursiveMethod(Main.java:7)<br/> at ErrorExample.recursiveMethod(Main.java:7)<br/> .<br/> .<br/> .</span></pre><p id="c518" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated"><strong class="is hj">异常处理:</strong>这是一种处理运行时错误的机制，这样可以维持应用程序的正常流程。异常通常会扰乱程序的正常流程，这就是我们使用异常处理的原因。</p><figure class="jo jp jq jr fd ij er es paragraph-image"><div role="button" tabindex="0" class="ik il di im bf in"><div class="er es ke"><img src="../Images/3232e9c43fb42893fd12932acd53b56b.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*fkR1yFOggP-BlVx0gldZ2Q.png"/></div></div><figcaption class="kf kg et er es kh ki bd b be z dx"><strong class="bd kj">Exception Hierarchy in java</strong></figcaption></figure><p id="24d6" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated">java中有两种类型的异常:</p><ol class=""><li id="f104" class="kk kl hi is b it iu ix iy jb km jf kn jj ko jn kp kq kr ks bi translated"><strong class="is hj">检查异常:</strong>这些异常在编译时被检查，看程序员是否处理过。如果程序中没有处理这些异常，将会出现编译错误。例如，SQLException、IOException、ClassNotFoundException等。</li><li id="abb1" class="kk kl hi is b it kt ix ku jb kv jf kw jj kx jn kp kq kr ks bi translated"><strong class="is hj">未检查的异常:</strong>这些异常是在运行时检查的，所以处理这些异常是程序员的责任。例如，ArithmeticException、NullPointerException、ArrayIndexOutOfBoundsException等。</li></ol><p id="e93f" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated"><strong class="is hj"> try块:</strong>这是一个由可能出现异常的语句组成的块。try块后面总是跟着catch块，在catch块中处理这些异常。try块后面必须跟catch块或finally块，或者两者都跟。</p><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="e323" class="jx jy hi jt b fi jz ka l kb kc">try{<br/>   //statements that may cause an exception<br/>}</span></pre><p id="da10" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated"><strong class="is hj"> catch块:</strong>处理try块中发生的异常的块。当try块中出现异常时，处理该异常的catch块将执行。</p><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="239e" class="jx jy hi jt b fi jz ka l kb kc">try<br/>{<br/>     //statements that may cause an exception<br/>}<br/>catch (Exception(type) e(object))‏<br/>{<br/>     //error handling code<br/>}</span></pre><figure class="jo jp jq jr fd ij er es paragraph-image"><div class="er es ky"><img src="../Images/92ab30aa28d609e44da0f32d7b7cb6cf.png" data-original-src="https://miro.medium.com/v2/resize:fit:1200/format:webp/1*7uRtqjF3mVZ4g0kUYIoUxg.png"/></div></figure><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="aa6e" class="jx jy hi jt b fi jz ka l kb kc">class Solution{<br/>      public static void main(String args[]){<br/>          int num1 = 10;<br/>          int num2 = 0;<br/>          try{<br/>             System.out.println("Statement 1");<br/>             System.out.println("Statement 2");<br/>             int result = num1 / num2;<br/>             System.out.println("Statement 4")</span><span id="9600" class="jx jy hi jt b fi kd ka l kb kc">          }catch(ArithmeticException e){<br/>              System.out.println("Number divide by Zero");<br/>           }<br/>      }<br/>  }</span><span id="680b" class="jx jy hi jt b fi kd ka l kb kc">Output: Statement 1<br/>        Statement 2<br/>        Number divide by Zero</span></pre><p id="0ed2" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated">在上面的示例中，当一个数被零除时，catch块捕获到一个ArithmeticException。发生异常的语句后面的代码块将永远不会被执行。</p><p id="a882" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated"><strong class="is hj"> finally block </strong>:无论是否发生异常，都是一定要执行的块。</p><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="708e" class="jx jy hi jt b fi jz ka l kb kc">try {<br/>    //Statements that may cause an exception<br/>}<br/>catch(Exception(type) object) {<br/>   //Handling exception<br/>}<br/>finally {<br/>   //Statements to be executed<br/>}</span></pre><figure class="jo jp jq jr fd ij er es paragraph-image"><div class="er es ky"><img src="../Images/dc1aaea97cd454f970a71283cff806fc.png" data-original-src="https://miro.medium.com/v2/resize:fit:1200/format:webp/1*V83hkjj2GCD16bT5C1YDcA.png"/></div></figure><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="10ff" class="jx jy hi jt b fi jz ka l kb kc">class Solution{<br/>      public static void main(String args[]){<br/>          int num1 = 10;<br/>          int num2 = 0;<br/>          try{<br/>             int result = num1 / num2;<br/>          }catch(ArithmeticException e){<br/>              System.out.println("Number divide by Zero");<br/>           }<br/>          finally{<br/>             System.out.println("finally block is executed");<br/>          }<br/>      }<br/>  }</span><span id="b893" class="jx jy hi jt b fi kd ka l kb kc">Output : Number divide by Zero<br/>         finally block is executed</span></pre><p id="1338" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated"><strong class="is hj"> throw: </strong>是一个关键字，用来抛出我们自己定制的异常。假设你想制作一个程序，允许年满18岁的人在选举中投票。然后我们可以使用<strong class="is hj"> throw </strong>关键字来抛出我们自己定制的异常，如果一个人的年龄在18岁以下，它将显示“你不允许投票”。</p><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="6ca8" class="jx jy hi jt b fi jz ka l kb kc">class Solution{<br/>      public static void main(String args[]){<br/>        int personAge1 = 18;<br/>        int personAge2 = 15;<br/>        checkEligibility(personAge1);<br/>        checkEligibility(personAge2);<br/>      }<br/>      <br/>      static void checkEligibility(int age){<br/>          if(age &lt; 18){<br/>          throw new ArithmeticException("You are not allowed to vote"); <br/>          }<br/>      else {<br/>         System.out.println("You are allowed to vote");<br/>      }<br/>      }<br/>}</span><span id="fbd9" class="jx jy hi jt b fi kd ka l kb kc">Output: Exception in thread "main" java.lang.ArithmeticException:                      You are not allowed to vote<br/>        at Solution.checkEligibility(Main.java:10)<br/>        at Solution.main(Main.java:12)</span></pre><p id="588e" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated"><strong class="is hj">抛出:</strong>主要用于声明异常。它告诉程序员可能会出现异常，所以最好提供异常处理代码来维持程序的流程。</p><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="45d6" class="jx jy hi jt b fi jz ka l kb kc">public void myMethod() throws ArithmeticException{<br/>  // Statements that might throw an exception <br/>}<br/><br/>public static void main(String args[]) { <br/>  try {<br/>    myMethod();<br/>  }<br/>  catch (ArithmeticException e) {<br/>    // Exception handling statements<br/>  }<br/>  catch (NullPointerException e) {<br/>    // Exception handling statements<br/>  }<br/>}</span></pre><p id="c8f9" class="pw-post-body-paragraph iq ir hi is b it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn hb bi translated">示例:</p><pre class="jo jp jq jr fd js jt ju jv aw jw bi"><span id="c151" class="jx jy hi jt b fi jz ka l kb kc">class M{  <br/> void method()throws IOException{  <br/>  throw new IOException("device error");  <br/> }  <br/>}  <br/>class Testthrows4{  <br/>   public static void main(String args[])throws IOException{ <br/>     M m=new M();  <br/>     m.method();  <br/>  <br/>    System.out.println("normal flow...");  <br/>  }  <br/>}</span><span id="94cf" class="jx jy hi jt b fi kd ka l kb kc">Output: Exception in thread "main" java.io.IOException: device error<br/>        at M.method(Main.java:10)<br/>        at Testthrows4.main(Main.java:16)</span></pre></div></div>    
</body>
</html>